### ISSUE TITLE
Openapi 3 not work with array

### ISSUE THREAD

**Issue by spinenkoia** [aamalev/aiohttp_apiset#123]
If you specify such a scheme
```
      parameters:
        - name: ids
          description: Some description
          required: false
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              format: uuid
```
Then an array of the following type comes to the backend
`['3bd604c2-6edd-4a77-8233-6f93a05b593b,51e01ea8-9517-4288-b63a-90e265cb4e2c']`

If you translate to the scheme of 3 versions, everything is fine
```
      parameters:
        - name: ids
          description: Some description
          required: false
          in: query
          type: array
          collectionFormat: csv
          items:
            type: string
            format: uuid
```
Version aiohtt_aipset = 0.9.13.2
