### ISSUE TITLE
Support for nullable fields.

### ISSUE THREAD

**Issue by abogushov** [aamalev/aiohttp_apiset#13]
Swagger does not allow nullable fields for schemas like this:

```yaml
DateInterval:
    type: object
    properties:
      from:
        type: string
        nullable: true
        format: date
        example: '2018-01-30'
      to:
        type: string
        nullable: true
        format: date
        example: '2018-01-30'
```

But if I remove `nullable: true` json-schema  validation cannot be passed.
