### ISSUE TITLE
Unexpected value passed to handler when calling endpoint and not specifying the value for an array query parameter

### ISSUE THREAD

**Issue by spinenkoia** [aamalev/aiohttp_apiset#166]
Calling an endpoint and not specifying the value for an array query parameter results in handler receiving ['']

For example , when requesting http://127.0.0.1/users ?user_ids= in the handler, instead of [] I get ["]

swagger shema:
```
  UserIdsParam:
    name: user_ids
    required: false
    in: query
    type: array
    collectionFormat: csv
    items:
      type: string
      format: uuid
```

Python version: 3.10.2
aiohttp_apiset vesion: 0.9.15
